:hardbreaks-option:


= social_network_system_design

System Design социальной сети для курса по System Design

image:https://img.shields.io/badge/License-MIT-black?style=for-the-badge[MIT License, link="./LICENSE"]


== функциональные требования
* функционал публикации постов, 
  посты могут быть с фото и без, 
  со следующими лимитами и возможностями 
  к содержимому одного поста:
  - количество фотографий к одному посту не превышает 12;
  - размер одной фотографии не должен превышать 10мб, общий размер всех фотографий к одному посту не должен превышать 100мб;
  - количество знаков в тексте не превышает 25 000;
  - минимальное количество знаков для поста не содержащего фотографии: 1.
  - возможность отметки геолокации во время публикации, вручную и с подхватыванием из геотэга фотографии;

* оценка и комментарии постов других путешественников;
* подписка на других путешественников, чтобы следить за их активностью;
* поиск популярных мест для путешествий и просмотр постов с этих мест;
* просмотр ленты других путешественников и ленты пользователя, основанной на подписках в обратном хронологическом порядке;


== нефункциональные требования

== расчет нагрузки
