:hardbreaks-option:


= social_network_system_design

System Design социальной сети для курса по System Design

image:https://img.shields.io/badge/License-MIT-black?style=for-the-badge[MIT License, link="./LICENSE"]


== функциональные требования
* функционал страницы пользователя:
  - каждый пользователь имеет страницу - ленту в обратном хронологическом порядке, которую могут просматривать другие пользователи;

* функционал публикации постов, 
  посты могут быть с фото и без, 
  со следующими лимитами и возможностями 
  к содержимому одного поста:
  - количество фотографий к одному посту не превышает 12;
  - размер одной фотографии не должен превышать 10мб, общий размер всех фотографий к одному посту не должен превышать 100мб;
  - количество знаков в тексте не превышает 25 000;
  - минимальное количество знаков для поста не содержащего фотографии: 1;
  - возможность отметки геолокации во время публикации, вручную и с подхватыванием из геотэга фотографии;

* функционал контроля цензуры, 
  иконка-кнопка "пожаловаться" к каждому посту:
  - если пост просмотрен не менее 5 раз, 
    и не менее 50% просмотревших воспользовались кнопкой, 
    пост автоматически удаляется 
    и пользователю блокируется возможность публиковать новые посты, 
    принятие решения о разблокировке и осуществление разблокировки 
    производится в рамках обращения в поддержку.

* функционал оценки,
  со следующими лимитами и возможностями:
  - каждый путешественник имеет возможность оценить любой пост по трехбальной шкале;

* функционал комментирования постов,
  со следующими лимитами и возможностями:
  - максимальная длина комментария 200 символов;
  - можно отвечать на комментарии, максимальная глубина вложенности: 10;
  - любой комментарий можно лайкать;
  - любой пост можно лайкнуть, вне возможности написать комментарий;

* функционал поиска, со следующими возможностями:
  - сортировка по популярности места (больше всего постов по этой локации);
  - фильтр по минимальному рейтингу;

* функционал подписок и просмотра ленты постов:
  - каждый путешественник имеется возможность подписаться на другого путешественника;
  - каждый пользователь имеет общую ленту в обратном хронологическом порядке, содержащую новые посты тех путешественников, на которых он подписан;

== нефункциональные требования – специфика и ограничения
* предполагаем 10000000 DAU;
* предполагаем, что каждый пользователь совершает в среднем 20 запросов ежедневно,
  из них 2 на загрузку нового поста;
  18 запросов на чтение;
* планируется использование приложения из любых стран,
  при этом имеется список из топ 10 стран откуда запросы на запись производятся наиболее часто;
* данные активных аккаунтов планируем храним всегда;
  под активным аккаунтом подразумеваем что выполняется хотя бы одно из условий:
  - имеется хотя бы один успешный вход в аккаунт за последние 100 лет;
  - на страницу аккаунта заходили другие пользователи в течение последних 10 лет;
* у пользователя может быть максимум 1 млрд подписчиков.
* минимальная скорость загрузки одной фотографии составляет 2мб/с,
  без учета ограничений скорости на стороне пользователя.
* availability 99,9%;
* high availability;
* scalability;

== расчет нагрузки
RPS read = 10000000 * 18 / 86 400 = 2083
RPS write = 10000000 * 2 / 86 400 = 231
RPS total = 2314

connections = 10000000 * 0.1 = 1000000
(10% DAU)
