:hardbreaks-option:


= social_network_system_design

System Design социальной сети для курса по System Design

image:https://img.shields.io/badge/License-MIT-black?style=for-the-badge[MIT License, link="./LICENSE"]


== функциональные требования
* функционал страницы пользователя:
  - каждый пользователь имеет страницу - ленту в обратном хронологическом порядке, которую могут просматривать другие пользователи.

* функционал публикации постов, 
  посты могут быть с фото и без, 
  со следующими лимитами и возможностями 
  к содержимому одного поста:
  - количество фотографий к одному посту не превышает 12;
  - размер одной фотографии не должен превышать 10мб, общий размер всех фотографий к одному посту не должен превышать 100мб;
  - количество знаков в тексте не превышает 25 000;
  - минимальное количество знаков для поста не содержащего фотографии: 1.
  - возможность отметки геолокации во время публикации, вручную и с подхватыванием из геотэга фотографии;

* функционал контроля цензуры, 
  иконка-кнопка "пожаловаться" к каждому посту:
  - если пост просмотрен не менее 5 раз, 
    и не менее 50% просмотревших воспользовались кнопкой, 
    пост автоматически удаляется 
    и пользователю блокируется возможность публиковать новые посты, 
    принятие решения о разблокировке и осуществление разблокировки 
    производится в рамках обращения в поддержку.

* оценка и комментарии постов других путешественников;
* подписка на других путешественников, чтобы следить за их активностью;
* поиск популярных мест для путешествий и просмотр постов с этих мест;
* просмотр ленты других путешественников и ленты пользователя, основанной на подписках в обратном хронологическом порядке;

* функционал подписок и ленты постов:
  - каждый путешественник имеется возможность подписаться на другого путешественника.
  - каждый пользователь имеет общую ленту в обратном хронологическом порядке, содержащую новые посты тех путешественников, на которых он подписан.



== нефункциональные требования

== расчет нагрузки
